sudo: required
services:
  - docker

before_install:
  - docker build -t joshwhieb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run joshwhieb/react-test npm test -- --coverage

after_success:
  - docker build -t joshwhieb/multi-client ./client
  - docker build -t joshwhieb/multi-nginx ./nginx
  - docker build -t joshwhieb/multi-server ./server
  - docker build -t joshwhieb/multi-worker ./worker
  # log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push joshwhieb/multi-client
  - docker push joshwhieb/multi-nginx
  - docker push joshwhieb/multi-server
  - docker push joshwhieb/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-393463177732
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  
    